import { z } from 'zod';

export const createMemberSchema = z.object({
  memberId: z.string().min(1, 'Member ID is required'),
  name: z.string().min(1, 'Name is required'),
  email: z.string().email('Invalid email'),
  phone: z.string().min(1, 'Phone is required'),
  photo: z.string().optional(),
  dob: z.string().optional().transform(str => str ? new Date(str) : undefined),
  bloodGroup: z.string().optional(),
  qualification: z.string().optional(),
  occupation: z.string().optional(),
  address: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  pincode: z.string().optional(),
  emergencyContactName: z.string().optional(),
  emergencyContactNumber: z.string().optional(),
  age: z.number().int().positive().optional(),
  gender: z.string(),
  caste: z.string().optional(),
  package: z.string(),
  status: z.string(),
  joinDate: z.string().transform((str) => new Date(str)),
  expiryDate: z.string().transform((str) => new Date(str)),
  discipline: z.string(),
  coach: z.string(),
  batch: z.string(),
  attendanceRate: z.number().min(0).max(100).default(0),
  totalPaid: z.number().min(0).default(0),
  dueAmount: z.number().min(0).default(0),
  nraiId: z.string().optional(),
  safetyExpiry: z.string().optional(),
  branchId: z.string().uuid('Invalid branch ID'),
});

export const updateMemberSchema = createMemberSchema.partial();
